server:
  port: 8085
  error:
    include-message: always
    include-binding-errors: always

# http://localhost:8091/h2-console
spring:
  # ===============================
  # DB
  # ===============================
  datasource:
    url: jdbc:mysql://localhost:3306/productDB
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 190477opor

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
